/** All Ukrainian UI strings for Învață Româna. Keys with placeholders use {count}/{total} literally. */
export const t = {
  appName: 'Învață Româna',
  startSession: 'Почати заняття',
  continue: 'Продовжити',
  check: 'Перевірити',
  next: 'Далі',
  again: 'Ще раз',
  gotIt: 'Зрозуміло',
  tryAgain: 'Спробуйте ще раз',
  great: 'Чудово!',
  close: 'Закрити',
  closeTier: 'Майже!',
  listen: 'Слухати',
  record: 'Записати',
  recording: 'Йде запис…',
  stop: 'Зупинити',
  playYours: 'Відтворити ваше',
  playModel: 'Відтворити зразок',
  showAnswer: 'Показати відповідь',
  typeWhatYouHear: 'Напишіть, що чуєте',
  whichWord: 'Яке слово?',
  yourTurn: 'Ваша черга',
  missionTitle: 'Завдання дня',
  missionDoForReal: 'Зробіть це по-справжньому',
  reviewsDue: 'Повторень заплановано',
  newWords: 'Нові слова',
  dailyGoal: 'Денна ціль',
  streak: 'Серія днів',
  wordsKnown: 'Відомих слів: {count} із {total}',
  settings: 'Налаштування',
  textSize: 'Розмір тексту',
  normal: 'Звичайний',
  large: 'Великий',
  done: 'Готово',
  sessionComplete: 'Заняття завершено!',
  xpEarned: 'Отримано досвіду: {count} XP',
  easy: 'Легко',
  correct: 'Правильно!',
  incorrect: 'Неправильно',
  itemNotFound: 'Картку не знайдено',
  correctIs: 'Правильна відповідь:',
  tapToAnswer: 'Натисніть слово, щоб скласти відповідь',
  clear: 'Очистити',
  typeAnswer: 'Введіть відповідь румунською',
  micPrivacyTitle: 'Мікрофон — тільки на вашому пристрої',
  micPrivacyBody: 'Запис використовується лише для відтворення на цьому пристрої та ніколи не надсилається на сервер.',
  micPrivacyOk: 'Зрозуміло, продовжити',
  warmUp: 'Розминка — повторення',
  dialogue: 'Діалог',
  grammar: 'Граматика',
  beginPractice: 'Почати практику',
  addedToReview: 'Нових слів у словнику: {count}',
  canDoNow: 'Новий крок зроблено — так тримати!',
  allCaughtUp: 'Усе повторено на сьогодні!',
  comeBackLater: 'Повертайтеся пізніше за новою порцією.',
  wordsKnownLabel: 'Відомі слова',
  reviewsDueShort: 'до повторення',
  newWordsShort: 'нові слова',
  resetProgress: 'Скинути прогрес',
  resetConfirm: 'Скинути весь прогрес? Цю дію не можна відмінити.',
  about: 'Про застосунок',
  aboutBody: 'Застосунок працює офлайн і зберігає прогрес лише на вашому пристрої.',
  dailyGoalItems: 'Слів на день: {count}',
  allDoneToday: 'Ціль на сьогодні виконано 🎉',
  diacriticHint: 'Зверніть увагу на «{letters}»',
  gameTitle: 'Швидка вікторина',
  gameTagline: 'Слухайте слово й оберіть переклад, поки не вийшов час.',
  gamePlay: 'Грати',
  gameWhatMeans: 'Що це означає?',
  gameRoundOf: 'Раунд {n} із {total}',
  gameScore: 'Рахунок',
  gameBest: 'Рекорд',
  gameStreakLabel: 'Поспіль',
  gameTimeUp: 'Час вийшов!',
  gameOver: 'Гру завершено!',
  gameCorrectOf: 'Правильних: {n} із {total}',
  gameNewBest: 'Новий рекорд! 🏆',
  gamePlayAgain: 'Грати ще',
  backToHome: 'На головну',
} as const
