/** All Ukrainian UI strings for Învață Româna. Keys with placeholders use {count}/{total} literally. */
export const t = {
  appName: 'Învață Româna',
  startSession: 'Почати заняття',
  continue: 'Продовжити',
  check: 'Перевірити',
  next: 'Далі',
  again: 'Ще раз',
  gotIt: 'Зрозуміло',
  tryAgain: 'Спробуйте ще раз',
  great: 'Чудово!',
  close: 'Закрити',
  listen: 'Слухати',
  record: 'Записати',
  recording: 'Йде запис…',
  stop: 'Зупинити',
  playYours: 'Відтворити ваше',
  playModel: 'Відтворити зразок',
  showAnswer: 'Показати відповідь',
  typeWhatYouHear: 'Напишіть, що чуєте',
  whichWord: 'Яке слово?',
  yourTurn: 'Ваша черга',
  missionTitle: 'Завдання дня',
  missionDoForReal: 'Зробіть це по-справжньому',
  reviewsDue: 'Повторень заплановано',
  newWords: 'Нові слова',
  dailyGoal: 'Денна ціль',
  streak: 'Серія днів',
  wordsKnown: 'Відомих слів: {count} із {total}',
  settings: 'Налаштування',
  textSize: 'Розмір тексту',
  normal: 'Звичайний',
  large: 'Великий',
  done: 'Готово',
  sessionComplete: 'Заняття завершено!',
  xpEarned: 'Отримано досвіду: {count} XP',
  easy: 'Легко',
  correct: 'Правильно!',
  incorrect: 'Неправильно',
  itemNotFound: 'Картку не знайдено',
  correctIs: 'Правильна відповідь:',
  tapToAnswer: 'Натисніть слово, щоб скласти відповідь',
  clear: 'Очистити',
} as const
